# Generated by Django 3.1.6 on 2021-02-19 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, db_index=True)),
                ('image', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=15)),
                ('first_name', models.CharField(db_index=True, max_length=20)),
                ('last_name', models.CharField(db_index=True, max_length=20)),
                ('facebook_account', models.URLField(blank=True, null=True)),
                ('twitter_account', models.URLField(blank=True, null=True)),
                ('instagram_account', models.URLField(blank=True, null=True)),
                ('twitch_account', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
